services:
  - type: web
    name: dropbox-index
    env: node
    plan: free
    buildCommand: yarn; yarn build
    startCommand: yarn start
    envVars:
      - key: APP_ID
        value: ''
      - key: APP_SECRET
        value: ''
      - key: REFRESH_TOKEN
        value: ''
      - key: NEXT_PUBLIC_TITLE
        value: PublicBox
