name: CI

on:
  push:
    branches-ignore: ['gh-pages']
    tags: ['*']
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '#skip-lint')"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Run Linter
        run: yarn run lint

  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '#skip-build')"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn run build
