name: NextJS Build Test

on:
  push:
    branches-ignore: [gh-pages]
    paths-ignore: ["*.md"]
  pull_request:
    branches-ignore: [gh-pages]
    paths-ignore: ["*.md"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install node_modules
        run: yarn install
      - name: Build NextJS
        run: yarn build
